name: generate

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: |
          npm config set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            bun run generate.ts
          else
            bun run generate.ts --dry
          fi
